version: '3'
services:

  stop:
    build:
      context: ./stopapp
      dockerfile: Dockerfile
    restart: always
    links:
      - dbmysql
    ports:
      - 8090:8080


  dbmysql:
    image: hypriot/rpi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stop
      MYSQL_HOST: localhost
    ports:
      - 3306:3306